export default{
    logo:require('../assets/images/logo.png'),
    newLogo:require('../assets/images/myLogo.png'),
    hideEye:require('../assets/images/hide.png'),
    seeEye:require('../assets/images/see.png'),
    applelogo:require('../assets/images/apple.png'),
    goodleLogo:require('../assets/images/google.png'),
    facebooklogo:require('../assets/images/facebook.png'),
    backAngle:require('../assets/images/backangle.png'),
    bellicon:require('../assets/images/bellicon.png'),
    downArrow:require('../assets/images/downArrow.png'),
    locationIcon:require('../assets/images/locationIcon.png'),
    searchIcon:require('../assets/images/searchIcon.png'),
    fliterIcon:require('../assets/images/fliterIcon.png'),
    ic_checked:require('../assets/images/ic_checked.png'),
    ic_unchecked:require('../assets/images/ic_unchecked.png'),
    logout:require('../assets/images/logout.png'),
    termsconditions:require('../assets/images/termsconditions.png'),
    about:require('../assets/images/about.png'),
    contactUs:require('../assets/images/contactUs.png'),
    profileicon:require('../assets/images/profileicon.png'),
    wallet:require('../assets/images/wallet.png'),
    walleticon:require('../assets/images/walleticon.png'),
    close:require('../assets/images/Close.png'),
    ic_home:require('../assets/images/ic_home.png'),
    ic_account:require('../assets/images/ic_account.png'),
    circleplus:require('../assets/images/circleplus.png'),
    empty:require('../assets/images/empty.png'),
    form:require('../assets/images/form.png'),
    languageIcon:require('../assets/images/languageIcon.png'),
    call:require('../assets/images/call.png'),
    whatsapp:require('../assets/images/whatsapp.png'),
    icMap: require('../assets/images/ic_map.png'),
    delete: require('../assets/images/delete.png'),
    edit: require('../assets/images/edit.png'),
    defaultProductImg: require('../assets/images/defaultProductImg.png'),
    clock: require('../assets/images/clock.png'),
    availability: require('../assets/images/availability.png'),
    offer: require('../assets/images/offer.png'),



    //New Start
    onboard1:require('../assets/newAssets/onboard1.png'),
    onboard2:require('../assets/newAssets/onboard2.png'),
    onboard3:require('../assets/newAssets/onboard3.png'),
    contactUsImg:require('../assets/newAssets/contactUs.png'),
    netflix:require('../assets/newAssets/netflix.jpeg'),
    dealBack:require('../assets/newAssets/dealBack.png'),
    backImage:require('../assets/newAssets/backImage.jpeg'),
    ic_search:require('../assets/newAssets/ic_search.png'),
    products:require('../assets/images/products.png'),
    pendingOrder:require('../assets/images/pendingOrder.png'),
    activeOrder:require('../assets/images/activeOrder.png'),
    cancelOrder:require('../assets/images/cancelOrder.png'),
    deliveredOrder:require('../assets/images/deliveredOrder.png'),
    transaction:require('../assets/images/transaction.png'),
    privacyPolicy:require('../assets/images/privacyPolicy.png'),
    lock:require('../assets/images/lock.png'),
    homeImg:require('../assets/newAssets/homeImg.png'),
}